/**
 * POST /api/journal/reflect
 *
 * Saves a journal entry and returns a personalised CBT reflection prompt.
 *
 * Auth: Required (Supabase session cookie). Returns 401 if unauthenticated.
 *
 * Request body:
 *   { content: string }  — the journal entry text
 *
 * Response:
 *   200 { reflectionPrompt: string }
 *   400 { error: "No content" }
 *   401 { error: "Unauthorized" }
 *
 * The reflection prompt is generated by claude-haiku-4-5-20251001 if ANTHROPIC_API_KEY is set;
 * otherwise a generic fallback question is used. Either way the entry is saved.
 *
 * The entry and prompt are stored in the journal_entries table (RLS: own rows only).
 */
import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import Anthropic from "@anthropic-ai/sdk";

const anthropic = process.env.ANTHROPIC_API_KEY && process.env.ANTHROPIC_API_KEY !== "placeholder"
  ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  : null;

export async function POST(req: NextRequest) {
  const { content } = await req.json();
  if (!content) return NextResponse.json({ error: "No content" }, { status: 400 });

  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Default prompt used when Anthropic is unavailable
  let reflectionPrompt = "What emotions came up as you wrote this? What might this journal entry be telling you about what you need right now?";

  if (anthropic) {
    const message = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 256,
      system: "You are a compassionate CBT-informed journal coach. Given a journal entry, generate one thoughtful, open-ended reflection question (2-3 sentences max) that helps the user explore their emotions and patterns more deeply.",
      messages: [{ role: "user", content }],
    });
    const block = message.content[0];
    reflectionPrompt = block.type === "text" ? block.text : reflectionPrompt;
  }

  // Save both the entry and the generated/fallback reflection prompt
  await supabase.from("journal_entries").insert({ user_id: user.id, content, reflection_prompt: reflectionPrompt });

  return NextResponse.json({ reflectionPrompt });
}
